version: "3"
services:

  simpleexporter:
    build: 
      context: ./sonarqube-prometheus-exporter
      dockerfile: Dockerfile
    image: sonarqube-prometheus-exporter:latest
    container_name: sqexporter
    restart: unless-stopped
    depends_on:
      setsonarpass:
        condition: service_completed_successfully
    environment:
      - SONAR_URL=http://sonarqube:9000
      - SONAR_USER=admin
      - SONAR_PASSWORD=newAdminPassword
    ports:
      - "9120:9120"

  prometheus:
    image: docker.io/prom/prometheus:v2.28.1
    container_name: prometheus
    ports:
      - 9090:9090
    # links:
    #   - sqexporter
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: docker.io/grafana/grafana:8.0.5
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_INSTALL_PLUGINS: grafana-polystat-panel,yesoreyeram-boomtable-panel
    links:
      - prometheus
    volumes:
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/default.yml
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/default.yml
      - ./grafana/dashboards:/var/lib/grafana/dashboards

volumes:
  postgresql_data:
  sonarqube_bundled-plugins:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_db:
  sonarqube_extensions:
